# Generated by Django 2.2.2 on 2019-07-05 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(choices=[(0, '5-10'), (1, '10-15'), (2, '15-20'), (3, '20-25'), (4, '25-30')], max_length=2)),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('weight', models.IntegerField(choices=[(0, 'less than 35'), (1, '35-40'), (2, '45-50'), (3, '50-60'), (3, '60-70'), (4, '70-80'), (5, '80-90'), (6, '90-100'), (7, 'greater than 100')])),
                ('height', models.IntegerField(choices=[(0, 'less than 3 feet'), (1, '3-3.5 feet'), (2, '3-3.5 feet'), (3, '3.6-4 feet'), (4, '4-4.5 feet'), (5, '4.6-5 feet'), (6, '5.1-5.5 feet'), (7, '5.6-6 feet'), (8, '6.1-6.5 feet'), (9, '6.6-7 feet')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
